#!/bin/bash
# Simple script to guide you through Tinker training setup

echo "============================================================"
echo "Arjun Writing Style - Tinker Training Setup"
echo "============================================================"
echo ""
echo "Your dataset is ready: arjun_writing_tinker.jsonl"
echo "  - 35 investment writing samples"
echo "  - ~270KB total size"
echo ""
echo "============================================================"
echo "EASIEST WAY: Use Tinker Web Interface"
echo "============================================================"
echo ""
echo "1. Go to: https://tinker.cool"
echo "   (Login with your account)"
echo ""
echo "2. Upload Dataset:"
echo "   - Click 'Datasets' → 'Upload'"
echo "   - Select: arjun_writing_tinker.jsonl"
echo ""
echo "3. Start Training:"
echo "   - Click 'Train New Model'"
echo "   - Base Model: meta-llama/Llama-3.2-3B-Instruct"
echo "   - LoRA Rank: 32"
echo "   - Learning Rate: 2e-5"
echo "   - Epochs: 3-5"
echo "   - Batch Size: 4-8"
echo "   - Model Name: arjun-writing-style"
echo ""
echo "4. Monitor:"
echo "   - Training runs on Tinker's cloud GPUs"
echo "   - Takes ~30-60 minutes"
echo "   - Check dashboard for progress"
echo ""
echo "============================================================"
echo "Your API Key: $TINKER_API_KEY"
echo "============================================================"
echo ""
echo "All training happens on Tinker's servers - no local GPU needed!"
echo ""
